"""Initial migration with all models

Revision ID: 9205142eb341
Revises: 
Create Date: 2026-02-04 11:57:48.136866

"""
from typing import Sequence, Union
import sys
from pathlib import Path

from alembic import op
import sqlalchemy as sa

# Add the parent directory to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
from app.models.conversation import GUID


# revision identifiers, used by Alembic.
revision: str = '9205142eb341'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('scammer_identifier', sa.String(), nullable=False),
    sa.Column('persona_id', GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'STALLING', 'COMPLETED', 'ABANDONED', name='conversationstatus'), nullable=False),
    sa.Column('scam_type', sa.String(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_scammer_identifier'), 'conversations', ['scammer_identifier'], unique=False)
    op.create_table('personas',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('communication_style', sa.Text(), nullable=False),
    sa.Column('backstory', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scammer_profiles',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('known_aliases', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('linked_intelligence', sa.JSON(), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scammer_profiles_identifier'), 'scammer_profiles', ['identifier'], unique=True)
    op.create_table('intelligence',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('conversation_id', GUID(length=36), nullable=False),
    sa.Column('artifact_type', sa.Enum('UPI_ID', 'BANK_ACCOUNT', 'IFSC_CODE', 'PHONE', 'URL', 'EMAIL', name='artifacttype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('conversation_id', GUID(length=36), nullable=False),
    sa.Column('sender_type', sa.Enum('SCAMMER', 'HONEYPOT', name='sendertype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('intelligence')
    op.drop_index(op.f('ix_scammer_profiles_identifier'), table_name='scammer_profiles')
    op.drop_table('scammer_profiles')
    op.drop_table('personas')
    op.drop_index(op.f('ix_conversations_scammer_identifier'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
